### ISSUE TITLE
TF3.8 - Retornar cursos por campus

### ISSUE THREAD

**Issue by DanMke** [ads-unigrade-2019-1/API#27]
Critérios de aceitação:
Fazer 4 endpoints, um para cada campus e retornar o nome de todos os cursos.
Um curso será o nome do curso + o nome da habilitação.

Prazo:
03/06

**Comment by gdeusdara** [comment]
entao, nao tem q retornar o Objeto curso inteiro? só o nome do curso e o nome da habilitação
